### ISSUE TITLE
老板，如果是字典服务有新增，要刷新，也是用事件机制嘛

### ISSUE THREAD

**Issue by zclcs** [houkunlin-starter/system-dict-starter#2]

**Comment by houkunlin** [comment]
`RefreshDictValueEvent` 事件适用于刷新单个或多个字典文本值（适用于字典的新增、修改、删除）。

`RefreshDictEvent` 事件适用于刷新整个完整的所有的字典文本信息（所有 `DictProvider` 的字典信息）

**Comment by zclcs** [comment]
> `RefreshDictValueEvent` 事件适用于刷新单个或多个字典文本值（适用于字典的新增、修改、删除）。
> 
> `RefreshDictEvent` 事件适用于刷新整个完整的所有的字典文本信息（所有 `DictProvider` 的字典信息）

![image](https://user-images.githubusercontent.com/50291896/140244080-17d1af58-69da-4d0b-a6b7-994b38f2b90a.png)
这个source对象到底是传啥值

**Comment by zclcs** [comment]
> RefreshDictValueEvent

RefreshDictValueEvent 事件要删除的话，是直接传Iterable哪个构造方法？

**Comment by houkunlin** [comment]
![](https://user-images.githubusercontent.com/50291896/140244080-17d1af58-69da-4d0b-a6b7-994b38f2b90a.png)
这个值没有具体的用到（SpringBoot事件中包含的东西），随便传一个不为 null 的信息就行了，例如：发起事件的说明文本

**Comment by zclcs** [comment]
有计划支持像地区字典，这种带父子结构关系的字典嘛

**Comment by houkunlin** [comment]
使用 `RefreshDictValueEvent` 删除字典，在 `DictValueVo#title` 字段为null时视为删除字典（必须有`DictValueVo#type`和`DictValueVo#value`两个字段值）

**Comment by houkunlin** [comment]
> 有计划支持像地区字典，这种带父子结构关系的字典嘛

目前只是单层数据，暂时没计划支持带父子结构的多层数据

**Comment by houkunlin** [comment]
> 有计划支持像地区字典，这种带父子结构关系的字典嘛

如果有好的想法和实现欢迎提PR

**Comment by zclcs** [comment]
> > 有计划支持像地区字典，这种带父子结构关系的字典嘛
> 
> 如果有好的想法和实现欢迎提PR

1

**Comment by zclcs** [comment]
![image](https://user-images.githubusercontent.com/50291896/140251971-f289829a-61b2-465b-a72b-644241249369.png)
![image](https://user-images.githubusercontent.com/50291896/140251997-7cc11216-8d4e-40d1-8329-89dfddbd3752.png)
![image](https://user-images.githubusercontent.com/50291896/140252013-6c362d4e-1440-4f61-9dd3-3690d9dc7c2b.png)
老板，字典刷新没有生效

**Comment by houkunlin** [comment]
`RefreshDictValueEvent` 事件目前只针对 Redis 的 `dict:v` 前缀的字典文本信息，因此 `dict:t` 的类型信息不会发生变动，这个问题下个版本我看看该怎样同步处理一下这种情况

**Comment by zclcs** [comment]
> `RefreshDictValueEvent` 事件目前只针对 Redis 的 `dict:v` 前缀的字典文本信息，因此 `dict:t` 的类型信息不会发生变动，这个问题下个版本我看看该怎样同步处理一下这种情况

加个直接放整个DictTypeVo的咋样，如果只是刷新**dict:v**没有啥意义，因为文本内容已经由后端返回了

**Comment by houkunlin** [comment]
这个可以有

**Comment by houkunlin** [comment]
已发布 `1.4.5` 版本 https://github.com/houkunlin-starter/system-dict-starter/releases/tag/v1.4.5

仓库同步需要至少4小时

**Comment by zclcs** [comment]
> 已发布 `1.4.5` 版本 https://github.com/houkunlin-starter/system-dict-starter/releases/tag/v1.4.5
> 
> 仓库同步需要至少4小时
![image](https://user-images.githubusercontent.com/50291896/140670373-23b86450-f237-422f-a94c-f7bb2a91c127.png)
![image](https://user-images.githubusercontent.com/50291896/140670384-06655888-bd6f-4c74-9fc0-171c35f2bd7d.png)
有个小问题，删除dict:v后，dict:t没有删除

**Comment by houkunlin** [comment]
这个场景确实是忘记判断了。
想了解一下像这样需要动态删除字典类型对象信息的场景都是用在什么地方？目前已知的一些用到字典的场景都是需要通过硬编码在前端的，也就是在开发阶段能够理出清单具体都有哪些字典类型（在运行阶段只需要维护数据，不需要增删字典类型），想了解看看都有哪些场景需要动态增删字典类型对象信息的

**Comment by houkunlin** [comment]
在 `1.4.5` 的版本，删除单个 `dict:v` 的值后，是能够自动更新 `dict:t` 里面的字典值列表的，但是存在删除所有 `dict:v` 后不会删除 `dict:t` 的内容的问题，这个是我忘记判断了

**Comment by houkunlin** [comment]
> 在 `1.4.5` 的版本，删除单个 `dict:v` 的值后，是能够自动更新 `dict:t` 里面的字典值列表的，但是存在删除所有 `dict:v` 后不会删除 `dict:t` 的内容的问题，这个是我忘记判断了

不过这个场景感觉好像没有删除的必要。例如：
有一个字典 `DictA` ，这个 `DictA` 在前端某个页面有被具体的使用到，假如后端把 `DictA` 所有的值列表都删除了，此时依旧存在 `DictA` 这个字典，但是 `DictA` 这个字典的值列表是一个空的集合对象，前端的页面能够正常加载显示，只不过这个字典项的地方没有可选的值。
如果后端把 `DictA` 所有值删除后，同时也删除 `DictA` 这个字典类型对象，那么前端的这个页面会不会出现报错导致无法打开的场景

**Comment by zclcs** [comment]
> > 在 `1.4.5` 的版本，删除单个 `dict:v` 的值后，是能够自动更新 `dict:t` 里面的字典值列表的，但是存在删除所有 `dict:v` 后不会删除 `dict:t` 的内容的问题，这个是我忘记判断了
> 
> 不过这个场景感觉好像没有删除的必要。例如： 有一个字典 `DictA` ，这个 `DictA` 在前端某个页面有被具体的使用到，假如后端把 `DictA` 所有的值列表都删除了，此时依旧存在 `DictA` 这个字典，但是 `DictA` 这个字典的值列表是一个空的集合对象，前端的页面能够正常加载显示，只不过这个字典项的地方没有可选的值。 如果后端把 `DictA` 所有值删除后，同时也删除 `DictA` 这个字典类型对象，那么前端的这个页面会不会出现报错导致无法打开的场景

这个只要规定好就行了，后端首先还是得保证逻辑无误才是。

**Comment by houkunlin** [comment]
下个修复版本加上这个

**Comment by zclcs** [comment]
![image](https://user-images.githubusercontent.com/50291896/140673727-fb3c6061-dd49-4454-a425-56f9750d4d56.png)
![image](https://user-images.githubusercontent.com/50291896/140673731-6ebf7b9b-69aa-4ec1-9830-b69208040706.png)
![image](https://user-images.githubusercontent.com/50291896/140673745-2f27c391-606b-4ce3-b70b-a2ab6978d69d.png)
还有个小问题，我这边删了22之后dict:v没删掉，dict:t倒是删了

**Comment by zclcs** [comment]
不过，按使用场景来说dict:v删不删都无关紧要了

**Comment by zclcs** [comment]
偶现bug，一会能删，一会删不了

**Comment by houkunlin** [comment]
处理事件的地方加了 `@Async` 异步注解，如果项目启用了异步注解功能，那么将会在异步处理刷新字典事件，也就可能会存在一些延时问题。

**Comment by zclcs** [comment]
应该不是异步的问题，项目没启用异步

**Comment by zclcs** [comment]
![image](https://user-images.githubusercontent.com/50291896/140675512-235e8cfa-be6c-4923-a775-70b45de50afd.png)
![image](https://user-images.githubusercontent.com/50291896/140675568-2eda9fb0-003e-4ffd-9e59-922bcde1edac.png)
![image](https://user-images.githubusercontent.com/50291896/140675559-50b7ab30-cc87-468e-a32a-0bce4d4d4e34.png)

这次是dict:v删了，dict:t没删

**Comment by houkunlin** [comment]
:scream: :sob:

**Comment by houkunlin** [comment]
稍候我加点关键日志打印到控制台

**Comment by houkunlin** [comment]
更新了一个快照版本 `1.4.5-BUILD-SNAPSHOT`

**Comment by zclcs** [comment]
> 更新了一个快照版本 `1.4.5-BUILD-SNAPSHOT`

![image](https://user-images.githubusercontent.com/50291896/140888421-25fbdb99-7b0f-40b3-8f35-3d8dc49e51f8.png)
换了版本没看到日志，日志级别是啥

**Comment by houkunlin** [comment]
debug 级别

**Comment by zclcs** [comment]
> debug 级别

包名是啥

**Comment by houkunlin** [comment]
包名： `com.houkunlin`

**Comment by zclcs** [comment]
> 包名： `com.houkunlin`

![image](https://user-images.githubusercontent.com/50291896/140892810-0e263eef-65b4-4b33-b677-f9fb0a272f6c.png)

**Comment by zclcs** [comment]
![image](https://user-images.githubusercontent.com/50291896/140892863-3404c45e-f392-4f18-bc60-dcd6989d1505.png)
这是新增
![image](https://user-images.githubusercontent.com/50291896/140892918-a3896771-56eb-4e08-b42d-755de8a0d96c.png)
这是删除
dict:t没更新

**Comment by houkunlin** [comment]
截图我看一下你发起事件时传的内容。
你是不是把一个 `Iterator` 对象传给 `IterUtil#asIterable` 方法转换成为 `Iterable` 对象了？
例如是不是类型下面这样：
```java
final DictValueVo build = DictValueVo.builder().dictType("test").value(2).title(null).build();
final List<DictValueVo> list = Collections.singletonList(build);
publisher.publishEvent(new RefreshDictValueEvent(IterUtil.asIterable(list.iterator())));
```

实际上是直接传一个List就可以了：
```java
final DictValueVo build = DictValueVo.builder().dictType("test").value(2).title(null).build();
final List<DictValueVo> list = Collections.singletonList(build);
publisher.publishEvent(new RefreshDictValueEvent(list));
```

**Comment by zclcs** [comment]
> 截图我看一下你发起事件时传的内容。 你是不是把一个 `Iterator` 对象传给 `IterUtil#asIterable` 方法转换成为 `Iterable` 对象了？ 例如是不是类型下面这样：
> 
> ```java
> final DictValueVo build = DictValueVo.builder().dictType("test").value(2).title(null).build();
> final List<DictValueVo> list = Collections.singletonList(build);
> publisher.publishEvent(new RefreshDictValueEvent(IterUtil.asIterable(list.iterator())));
> ```
> 
> 实际上是直接传一个List就可以了：
> 
> ```java
> final DictValueVo build = DictValueVo.builder().dictType("test").value(2).title(null).build();
> final List<DictValueVo> list = Collections.singletonList(build);
> publisher.publishEvent(new RefreshDictValueEvent(list));
> ```

是的，这里被误导了，已经可以了

**Comment by houkunlin** [comment]
> 有计划支持像地区字典，这种带父子结构关系的字典嘛

`1.4.6-BUILD-SNAPSHOT` 增加了一个树形结构数据的字典文本转换支持，目前暂未发布正式版，你可以先试一下看看行不行。
在 [src/test/java/com/houkunlin/system/dict/starter/TreeDataTest.java](https://github.com/houkunlin-starter/system-dict-starter/blob/main/src/test/java/com/houkunlin/system/dict/starter/TreeDataTest.java) 有简单的使用示例

**Comment by zclcs** [comment]
> > 有计划支持像地区字典，这种带父子结构关系的字典嘛
> 
> `1.4.6-BUILD-SNAPSHOT` 增加了一个树形结构数据的字典文本转换支持，目前暂未发布正式版，你可以先试一下看看行不行。 在 [src/test/java/com/houkunlin/system/dict/starter/TreeDataTest.java](https://github.com/houkunlin-starter/system-dict-starter/blob/main/src/test/java/com/houkunlin/system/dict/starter/TreeDataTest.java) 有简单的使用示例

好

**Comment by zclcs** [comment]
能加个自定义redis键嘛

**Comment by houkunlin** [comment]
自定义Redis的前缀？

**Comment by zclcs** [comment]
> 自定义Redis的前缀？

是的

**Comment by houkunlin** [comment]
已发布的 `v1.4.7` 版本增加自定义前缀功能；

```yaml
system:
  dict:
    store-key:
      # 树结构父级值的前缀
      parent-prefix: ''
      # 数据字典类型对象前缀
      type-prefix: ''
      # 数据字典值文本前缀
      value-prefix: ''
```
