### ISSUE TITLE
sorted

### ISSUE THREAD

**Issue by itmagus** [houkunlin-starter/system-dict-starter#3]
sorted 不是排序的吗，怎么用哈，咋看代码里，都放的是0
DictEnum 里没有 sorted，DictTypeBuilder add也没有

**Comment by houkunlin** [comment]
之前的设计是为了给前端预留的字段，DictEnum 是枚举，默认按照定义的顺序展示。
主要是给那些实现了 `DictProvider` 自行提供的字典数据用的

**Comment by itmagus** [comment]
return DictTypeVo.newBuilder("dictHobby", "爱好")
            .add(1, "打篮球")
            .add(2, "踢足球")
            .add(3, "打羽毛球")
            .add(4, "打排球")
            .add(5, "玩手机")
            .add(6, "看电影")
            .build();
这个add，sorted字段也没放出来哈
https://github.com/houkunlin-starter/system-dict-starter/blob/main/system-dict-examples/examples-provider/src/main/java/com/examples/DbDictProvider.java
DictProvider的DEMO

**Comment by houkunlin** [comment]
DictTypeVo.newBuilder 手动构建的字典列表默认按照代码顺序，sorted这个字段的方法忘记加了
