### ISSUE TITLE
升级一波 spring boot 3.1.x

### ISSUE THREAD

**Issue by opcooc** [houkunlin-starter/system-dict-starter#4]

**Comment by houkunlin** [comment]
`v1.4.11` 版本在 SpringBoot3.1.x 下好像是可以正常使用的，你先试试看看，我这边试了一下暂时没发现问题，有问题的话反馈一下详细的情况，我倒时候再排查看看。

这个工具是没有自动配置的，需要在启动类上使用 `@SystemDictScan` 注解的

**Comment by opcooc** [comment]
可以
